### PR TITLE
Add secret key

### PR DESCRIPTION
**Pull request by georgmkd**
I added a key parameter to the URL and updated/wrote tests with it.
Wrote tests regarding the secretKey parameter "key" in URL, at the tests_flask_routes.py and test_url_builder.py.

### CODE REVIEW

**Comment by brentkastner** [comment]
I think there is a problem with the implementation here. Where is the secret key being stored between runs... following the existing pattern i think you need to add it to the runs table so that it is in the context of nextrun and available when building up the urls for the usetrace call. This works on the first but would fail because the secret key isn't available for subsequent runs....

**Comment by brentkastner** [comment]
https://github.com/brentkastner/trace_orchestrator/issues/3

**Comment by georgmkd** [comment]
I added a commit to store the secret key in the runs table and then use it in the next trace run from it

**Comment by brentkastner** [comment]
This looks excellent! Nice job

**Pull request merged**
